import { AssessmentQuestion } from "../types";

export const coupleQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "emotional_connection",
    text: "How deeply connected and emotionally understood do you feel in your relationship?",
    description: "Emotional safety is the foundation of relationship wellness.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q6_opt1", text: "Extremely connected", score: 5 },
      { id: "cpl_q6_opt2", text: "Mostly connected", score: 4 },
      { id: "cpl_q6_opt3", text: "Sometimes connected", score: 3 },
      { id: "cpl_q6_opt4", text: "Somewhat disconnected", score: 2 },
      { id: "cpl_q6_opt5", text: "Completely disconnected", score: 1 },
    ],
  },
  {
    id: 7,
    key: "conflict_resolution",
    text: "How constructively do you and your partner resolve disagreements or misunderstandings?",
    description: "Healthy communication during friction determines relationship resilience.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q7_opt1", text: "Very constructively", score: 5 },
      { id: "cpl_q7_opt2", text: "Mostly calmly", score: 4 },
      { id: "cpl_q7_opt3", text: "Sometimes heated / silent", score: 3 },
      { id: "cpl_q7_opt4", text: "Frequently argue / avoid", score: 2 },
      { id: "cpl_q7_opt5", text: "Destructively / toxic", score: 1 },
    ],
  },
  {
    id: 8,
    key: "goal_alignment",
    text: "How aligned are you and your partner on future goals (careers, finances, family)?",
    description: "Shared values and goals keep couples moving in the same direction.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q8_opt1", text: "Perfectly aligned", score: 5 },
      { id: "cpl_q8_opt2", text: "Mostly aligned", score: 4 },
      { id: "cpl_q8_opt3", text: "Somewhat aligned", score: 3 },
      { id: "cpl_q8_opt4", text: "Mainly misaligned", score: 2 },
      { id: "cpl_q8_opt5", text: "Completely conflicted", score: 1 },
    ],
  },
  {
    id: 9,
    key: "partner_support",
    text: "How supported do you feel by your partner in pursuing your individual growth and dreams?",
    description: "Support for individuality within a relationship prevents feelings of suffocation.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q9_opt1", text: "Highly supported", score: 5 },
      { id: "cpl_q9_opt2", text: "Mostly supported", score: 4 },
      { id: "cpl_q9_opt3", text: "Sometimes supported", score: 3 },
      { id: "cpl_q9_opt4", text: "Rarely supported", score: 2 },
      { id: "cpl_q9_opt5", text: "Actively discouraged / held back", score: 1 },
    ],
  },
  {
    id: 10,
    key: "quality_time",
    text: "How satisfied are you with the amount of focused, quality time you spend together?",
    description: "Dedicated bonding moments keep relationships lively and strong.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q10_opt1", text: "Very satisfied", score: 5 },
      { id: "cpl_q10_opt2", text: "Mostly satisfied", score: 4 },
      { id: "cpl_q10_opt3", text: "Sometimes busy", score: 3 },
      { id: "cpl_q10_opt4", text: "Rarely spend focused time", score: 2 },
      { id: "cpl_q10_opt5", text: "No quality time at all", score: 1 },
    ],
  },
  {
    id: 11,
    key: "financial_harmony",
    text: "How comfortably do you and your partner discuss and manage money together?",
    description: "Financial tension is one of the most common causes of relationship strain.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q11_opt1", text: "Very comfortably / aligned", score: 5 },
      { id: "cpl_q11_opt2", text: "Mostly aligned", score: 4 },
      { id: "cpl_q11_opt3", text: "Sometimes stressed", score: 3 },
      { id: "cpl_q11_opt4", text: "Frequent money arguments", score: 2 },
      { id: "cpl_q11_opt5", text: "Complete financial conflict", score: 1 },
    ],
  },
  {
    id: 12,
    key: "relationship_trust",
    text: "How secure and trusting do you feel in your partner's loyalty and commitment?",
    description: "Trust is the foundational pillar that guarantees relationship safety.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q12_opt1", text: "Completely secure & trusting", score: 5 },
      { id: "cpl_q12_opt2", text: "Mostly secure", score: 4 },
      { id: "cpl_q12_opt3", text: "Occasionally insecure", score: 3 },
      { id: "cpl_q12_opt4", text: "Frequently anxious", score: 2 },
      { id: "cpl_q12_opt5", text: "No trust / broken bond", score: 1 },
    ],
  },
  {
    id: 13,
    key: "chore_sharing",
    text: "How satisfied are you with the distribution of domestic and household tasks?",
    description: "Uneven workloads at home create resentment and exhaustion.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q13_opt1", text: "Very fairly shared", score: 5 },
      { id: "cpl_q13_opt2", text: "Mostly fair", score: 4 },
      { id: "cpl_q13_opt3", text: "Somewhat uneven", score: 3 },
      { id: "cpl_q13_opt4", text: "Highly uneven / stressful", score: 2 },
      { id: "cpl_q13_opt5", text: "Carry the entire load alone", score: 1 },
    ],
  },
  {
    id: 14,
    key: "emotional_expression",
    text: "How comfortably can you express your vulnerable feelings and concerns to your partner?",
    description: "Vulnerability builds trust and fosters deep emotional bonds.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q14_opt1", text: "Extremely comfortably", score: 5 },
      { id: "cpl_q14_opt2", text: "Mostly comfortably", score: 4 },
      { id: "cpl_q14_opt3", text: "Sometimes hesitant", score: 3 },
      { id: "cpl_q14_opt4", text: "Rarely share vulnerability", score: 2 },
      { id: "cpl_q14_opt5", text: "Unable to express myself", score: 1 },
    ],
  },
  {
    id: 15,
    key: "external_stress_buffer",
    text: "How well do you and your partner support each other against external stresses (work, extended family)?",
    description: "Standing as a team against external stress strengthens your bond.",
    type: "category",
    category: "couple",
    options: [
      { id: "cpl_q15_opt1", text: "Excellently supportive team", score: 5 },
      { id: "cpl_q15_opt2", text: "Mostly supportive", score: 4 },
      { id: "cpl_q15_opt3", text: "Sometimes let stress in", score: 3 },
      { id: "cpl_q15_opt4", text: "External stress creates arguments", score: 2 },
      { id: "cpl_q15_opt5", text: "Completely overwhelmed by external stress", score: 1 },
    ],
  },
];
