import { AssessmentQuestion } from "../types";

export const familyQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "family_communication",
    text: "How open and respectful is the daily communication among members in your household?",
    description: "Healthy communication channels support household cohesion and conflict resolution.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q6_opt1", text: "Very open & respectful", score: 5 },
      { id: "fam_q6_opt2", text: "Mostly positive", score: 4 },
      { id: "fam_q6_opt3", text: "Sometimes guarded / quiet", score: 3 },
      { id: "fam_q6_opt4", text: "Frequently tense", score: 2 },
      { id: "fam_q6_opt5", text: "Completely broken communication", score: 1 },
    ],
  },
  {
    id: 7,
    key: "family_conflict",
    text: "How often do unresolved domestic arguments or tension affect the calm in your home?",
    description: "Frequent domestic friction drains emotional energy and resilience.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q7_opt1", text: "Almost never", score: 5 },
      { id: "fam_q7_opt2", text: "Rarely", score: 4 },
      { id: "fam_q7_opt3", text: "Sometimes", score: 3 },
      { id: "fam_q7_opt4", text: "Frequently", score: 2 },
      { id: "fam_q7_opt5", text: "Almost constantly tense", score: 1 },
    ],
  },
  {
    id: 8,
    key: "family_bonding",
    text: "How often does your household set aside quality time to connect or share meals together?",
    description: "Rituals and shared time build strong roots of family support.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q8_opt1", text: "Daily or almost daily", score: 5 },
      { id: "fam_q8_opt2", text: "Multiple times a week", score: 4 },
      { id: "fam_q8_opt3", text: "Once in a while", score: 3 },
      { id: "fam_q8_opt4", text: "Rarely connect", score: 2 },
      { id: "fam_q8_opt5", text: "Never spend quality time", score: 1 },
    ],
  },
  {
    id: 9,
    key: "family_support",
    text: "How confident do you feel that your family members would support you during a crisis?",
    description: "Perceived family support is a key buffer against external life crises.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q9_opt1", text: "Extremely confident", score: 5 },
      { id: "fam_q9_opt2", text: "Mostly confident", score: 4 },
      { id: "fam_q9_opt3", text: "Sometimes confident", score: 3 },
      { id: "fam_q9_opt4", text: "Rarely confident", score: 2 },
      { id: "fam_q9_opt5", text: "Not supportive at all", score: 1 },
    ],
  },
  {
    id: 10,
    key: "individual_family_balance",
    text: "How well does your household balance collective family needs with your individual space?",
    description: "Maintaining personal boundaries within the family is crucial for individual growth.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q10_opt1", text: "Excellently balanced", score: 5 },
      { id: "fam_q10_opt2", text: "Mostly balanced", score: 4 },
      { id: "fam_q10_opt3", text: "Sometimes crowded / intrusive", score: 3 },
      { id: "fam_q10_opt4", text: "Rarely get personal space", score: 2 },
      { id: "fam_q10_opt5", text: "No individual freedom at all", score: 1 },
    ],
  },
  {
    id: 11,
    key: "household_harmony",
    text: "How smoothly are daily household tasks and organizational responsibilities coordinated?",
    description: "Domestic chore friction is a major contributor to family stress.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q11_opt1", text: "Very smoothly / shared fairly", score: 5 },
      { id: "fam_q11_opt2", text: "Mostly organized", score: 4 },
      { id: "fam_q11_opt3", text: "Sometimes chaotic", score: 3 },
      { id: "fam_q11_opt4", text: "Frequently uncoordinated", score: 2 },
      { id: "fam_q11_opt5", text: "Complete chaos / constant conflict", score: 1 },
    ],
  },
  {
    id: 12,
    key: "family_finances",
    text: "How much stress or anxiety do household expenses, bills, or mortgage payments cause?",
    description: "Shared financial stress affects all members of the household.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q12_opt1", text: "Almost no stress", score: 5 },
      { id: "fam_q12_opt2", text: "Minimal stress", score: 4 },
      { id: "fam_q12_opt3", text: "Moderate stress", score: 3 },
      { id: "fam_q12_opt4", text: "High stress", score: 2 },
      { id: "fam_q12_opt5", text: "Severe financial crisis", score: 1 },
    ],
  },
  {
    id: 13,
    key: "home_sanctuary",
    text: "How safe, peaceful, and restoring does your home environment feel to you?",
    description: "Your home environment should act as a sanctuary for mental restoration.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q13_opt1", text: "A complete sanctuary", score: 5 },
      { id: "fam_q13_opt2", text: "Mostly peaceful", score: 4 },
      { id: "fam_q13_opt3", text: "Somewhat noisy / restless", score: 3 },
      { id: "fam_q13_opt4", text: "Stressful / tense", score: 2 },
      { id: "fam_q13_opt5", text: "Not safe or peaceful at all", score: 1 },
    ],
  },
  {
    id: 14,
    key: "family_values",
    text: "How aligned are family members on values, behavioral rules, and mutual respect?",
    description: "Misaligned family values or rules create constant friction and rebellion.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q14_opt1", text: "Highly aligned", score: 5 },
      { id: "fam_q14_opt2", text: "Mostly aligned", score: 4 },
      { id: "fam_q14_opt3", text: "Sometimes clash", score: 3 },
      { id: "fam_q14_opt4", text: "Frequently clash", score: 2 },
      { id: "fam_q14_opt5", text: "Total division / clashing", score: 1 },
    ],
  },
  {
    id: 15,
    key: "family_resilience",
    text: "How adaptably does your family handle major changes, transitions, or external challenges?",
    description: "Adaptive resilience determines how families handle collective life hurdles.",
    type: "category",
    category: "family",
    options: [
      { id: "fam_q15_opt1", text: "Extremely resilient & united", score: 5 },
      { id: "fam_q15_opt2", text: "Mostly adaptable", score: 4 },
      { id: "fam_q15_opt3", text: "Sometimes divided", score: 3 },
      { id: "fam_q15_opt4", text: "Difficult to adjust", score: 2 },
      { id: "fam_q15_opt5", text: "Crumbles under stress", score: 1 },
    ],
  },
];
