import { AssessmentQuestion } from "../types";

export const menQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "vulnerability_stigma",
    text: "How comfortable do you feel opening up about your vulnerabilities, stress, or worries to others?",
    description: "Societal pressure on men to appear tough often prevents them from seeking help.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q6_opt1", text: "Extremely comfortable", score: 5 },
      { id: "men_q6_opt2", text: "Mostly comfortable", score: 4 },
      { id: "men_q6_opt3", text: "Sometimes hesitant", score: 3 },
      { id: "men_q6_opt4", text: "Very uncomfortable", score: 2 },
      { id: "men_q6_opt5", text: "Not comfortable at all / hide it", score: 1 },
    ],
  },
  {
    id: 7,
    key: "provider_pressure",
    text: "How often do you feel stressed by societal or family expectations to be the primary provider?",
    description: "The pressure of breadwinning is a significant component of male stress.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q7_opt1", text: "Almost never", score: 5 },
      { id: "men_q7_opt2", text: "Occasionally", score: 4 },
      { id: "men_q7_opt3", text: "Sometimes stressed", score: 3 },
      { id: "men_q7_opt4", text: "Frequently stressed", score: 2 },
      { id: "men_q7_opt5", text: "Constantly overwhelmed by pressure", score: 1 },
    ],
  },
  {
    id: 8,
    key: "emotional_sharing",
    text: "How satisfied are you with the support, trust, and depth of your friendships with other men?",
    description: "Having trusted friends is critical for men to vent and feel supported.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q8_opt1", text: "Very satisfied", score: 5 },
      { id: "men_q8_opt2", text: "Mostly satisfied", score: 4 },
      { id: "men_q8_opt3", text: "Somewhat neutral", score: 3 },
      { id: "men_q8_opt4", text: "Rarely share deep topics", score: 2 },
      { id: "men_q8_opt5", text: "Completely isolated / no friends", score: 1 },
    ],
  },
  {
    id: 9,
    key: "physical_fitness",
    text: "How consistent are you with physical exercise, outdoor time, or body movement habits?",
    description: "Physical movement plays a massive role in regulating testosterone and stress levels.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q9_opt1", text: "Very consistent (4+ days/wk)", score: 5 },
      { id: "men_q9_opt2", text: "Mostly active", score: 4 },
      { id: "men_q9_opt3", text: "Sometimes active", score: 3 },
      { id: "men_q9_opt4", text: "Rarely active", score: 2 },
      { id: "men_q9_opt5", text: "Completely sedentary", score: 1 },
    ],
  },
  {
    id: 10,
    key: "life_purpose",
    text: "How clear is your current sense of purpose, goals, or direction in life?",
    description: "Having a clear mission and goals is a major protective factor for men's mental health.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q10_opt1", text: "Extremely clear & driven", score: 5 },
      { id: "men_q10_opt2", text: "Mostly clear", score: 4 },
      { id: "men_q10_opt3", text: "Somewhat unsure", score: 3 },
      { id: "men_q10_opt4", text: "Mainly lost / searching", score: 2 },
      { id: "men_q10_opt5", text: "No direction at all", score: 1 },
    ],
  },
  {
    id: 11,
    key: "anger_management",
    text: "How constructively do you manage feelings of frustration, irritation, or anger?",
    description: "Constructive expression of anger prevents destructive behavioral outbreaks.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q11_opt1", text: "Very constructively / calmly", score: 5 },
      { id: "men_q11_opt2", text: "Mostly calmly", score: 4 },
      { id: "men_q11_opt3", text: "Sometimes snap / yell", score: 3 },
      { id: "men_q11_opt4", text: "Frequently lose control", score: 2 },
      { id: "men_q11_opt5", text: "Highly aggressive / shut down", score: 1 },
    ],
  },
  {
    id: 12,
    key: "job_identity",
    text: "How closely is your sense of self-worth tied to your career performance or salary?",
    description: "Tying self-worth entirely to professional outputs creates emotional volatility.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q12_opt1", text: "Not tied at all / healthy balance", score: 5 },
      { id: "men_q12_opt2", text: "Slightly tied", score: 4 },
      { id: "men_q12_opt3", text: "Moderately tied", score: 3 },
      { id: "men_q12_opt4", text: "Highly dependent on career success", score: 2 },
      { id: "men_q12_opt5", text: "Entirely defined by my job", score: 1 },
    ],
  },
  {
    id: 13,
    key: "brotherhood",
    text: "How often do you speak with other men about your personal struggles or career challenges?",
    description: "Venting to a trusted group of peers prevents isolation and emotional overload.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q13_opt1", text: "Frequently / weekly", score: 5 },
      { id: "men_q13_opt2", text: "Occasionally", score: 4 },
      { id: "men_q13_opt3", text: "Rarely", score: 3 },
      { id: "men_q13_opt4", text: "Only in extreme crisis", score: 2 },
      { id: "men_q13_opt5", text: "Never share with other men", score: 1 },
    ],
  },
  {
    id: 14,
    key: "decompression_time",
    text: "How effectively do you set time aside to mentally decompress and recharge without screens?",
    description: "Quiet decompression habits let your nervous system recover from daily stresses.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q14_opt1", text: "Very effectively", score: 5 },
      { id: "men_q14_opt2", text: "Mostly effectively", score: 4 },
      { id: "men_q14_opt3", text: "Sometimes effectively", score: 3 },
      { id: "men_q14_opt4", text: "Rarely decompress", score: 2 },
      { id: "men_q14_opt5", text: "Never take time to reset", score: 1 },
    ],
  },
  {
    id: 15,
    key: "health_monitoring",
    text: "How proactively are you tracking and monitoring your physical health and wellness indicators?",
    description: "Prioritizing primary health indicators is key to preventing long-term fatigue.",
    type: "category",
    category: "men",
    options: [
      { id: "men_q15_opt1", text: "Highly proactive", score: 5 },
      { id: "men_q15_opt2", text: "Mostly aware", score: 4 },
      { id: "men_q15_opt3", text: "Sometimes check", score: 3 },
      { id: "men_q15_opt4", text: "Ignore until sick", score: 2 },
      { id: "men_q15_opt5", text: "Never monitor my health", score: 1 },
    ],
  },
];
