import { AssessmentQuestion } from "../types";

export const otherQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "general_stress",
    text: "How often have you felt overwhelmed by daily pressures or unexpected challenges recently?",
    description: "Tracking general life stress helps identify when workloads or routines become difficult to manage.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q6_opt1", text: "Almost never", score: 5 },
      { id: "oth_q6_opt2", text: "Occasionally", score: 4 },
      { id: "oth_q6_opt3", text: "Sometimes", score: 3 },
      { id: "oth_q6_opt4", text: "Frequently", score: 2 },
      { id: "oth_q6_opt5", text: "Almost constantly", score: 1 },
    ],
  },
  {
    id: 7,
    key: "emotional_balance",
    text: "How easily can you calm down or restore focus when encountering emotional triggers?",
    description: "Emotional balance supports general wellness and resilience during daily challenges.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q7_opt1", text: "Very easily", score: 5 },
      { id: "oth_q7_opt2", text: "Mostly easily", score: 4 },
      { id: "oth_q7_opt3", text: "Sometimes difficult", score: 3 },
      { id: "oth_q7_opt4", text: "Frequently difficult", score: 2 },
      { id: "oth_q7_opt5", text: "Unable to balance at all", score: 1 },
    ],
  },
  {
    id: 8,
    key: "mindfulness_practice",
    text: "How regularly do you dedicate time to self-care, breathing, or quiet reflection?",
    description: "Regular self-reflection and breathing exercises strengthen your emotional coping capacity.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q8_opt1", text: "Every day", score: 5 },
      { id: "oth_q8_opt2", text: "Several times a week", score: 4 },
      { id: "oth_q8_opt3", text: "Once a week", score: 3 },
      { id: "oth_q8_opt4", text: "Rarely", score: 2 },
      { id: "oth_q8_opt5", text: "Never", score: 1 },
    ],
  },
  {
    id: 9,
    key: "sleep_quality",
    text: "How rested and energized do you feel when waking up in the morning?",
    description: "Deep, restorative sleep is the foundation of mental clarity and energy levels.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q9_opt1", text: "Fully rested & energized", score: 5 },
      { id: "oth_q9_opt2", text: "Mostly rested", score: 4 },
      { id: "oth_q9_opt3", text: "Somewhat tired", score: 3 },
      { id: "oth_q9_opt4", text: "Highly fatigued", score: 2 },
      { id: "oth_q9_opt5", text: "Completely exhausted", score: 1 },
    ],
  },
  {
    id: 10,
    key: "personal_growth",
    text: "How optimistic and motivated do you feel about your personal development and future journey?",
    description: "Having clear self-goals supports motivation and builds life satisfaction.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q10_opt1", text: "Highly optimistic & clear", score: 5 },
      { id: "oth_q10_opt2", text: "Mostly positive", score: 4 },
      { id: "oth_q10_opt3", text: "Somewhat neutral", score: 3 },
      { id: "oth_q10_opt4", text: "Uncertain / anxious", score: 2 },
      { id: "oth_q10_opt5", text: "Lacking direction entirely", score: 1 },
    ],
  },
  {
    id: 11,
    key: "social_connections",
    text: "How satisfied are you with the quality of support you receive from family, peers, or communities?",
    description: "Meaningful support groups build belonging and prevent feelings of isolation.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q11_opt1", text: "Completely satisfied", score: 5 },
      { id: "oth_q11_opt2", text: "Mostly satisfied", score: 4 },
      { id: "oth_q11_opt3", text: "Neutral", score: 3 },
      { id: "oth_q11_opt4", text: "Somewhat isolated", score: 2 },
      { id: "oth_q11_opt5", text: "Completely disconnected", score: 1 },
    ],
  },
  {
    id: 12,
    key: "physical_activity",
    text: "How regularly are you able to engage in physical movement or outdoor activities?",
    description: "Active physical movement releases endorphins and reduces stress build-up.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q12_opt1", text: "Almost daily", score: 5 },
      { id: "oth_q12_opt2", text: "Few times a week", score: 4 },
      { id: "oth_q12_opt3", text: "Weekly", score: 3 },
      { id: "oth_q12_opt4", text: "Rarely", score: 2 },
      { id: "oth_q12_opt5", text: "Never", score: 1 },
    ],
  },
  {
    id: 13,
    key: "routine_control",
    text: "How much control do you feel you have over your daily schedule and balance?",
    description: "Sovereignty over your schedule reduces anxiety and prevents burnout.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q13_opt1", text: "Complete control", score: 5 },
      { id: "oth_q13_opt2", text: "Mostly in control", score: 4 },
      { id: "oth_q13_opt3", text: "Sometimes overwhelmed", score: 3 },
      { id: "oth_q13_opt4", text: "Rarely in control", score: 2 },
      { id: "oth_q13_opt5", text: "No control at all", score: 1 },
    ],
  },
  {
    id: 14,
    key: "work_life_balance",
    text: "How comfortable are you drawing boundaries between work or commitments and your personal time?",
    description: "Clear boundaries prevent daily tasks from encroaching on essential recovery space.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q14_opt1", text: "Very comfortable / supported", score: 5 },
      { id: "oth_q14_opt2", text: "Mostly manageable", score: 4 },
      { id: "oth_q14_opt3", text: "Sometimes cross boundaries", score: 3 },
      { id: "oth_q14_opt4", text: "Frequently overworked", score: 2 },
      { id: "oth_q14_opt5", text: "Severely burnt out", score: 1 },
    ],
  },
  {
    id: 15,
    key: "coping_resilience",
    text: "How effectively do you manage unexpected stressors or anxiety loops in daily life?",
    description: "Developing resilient mental skills prevents long-term wellness decline.",
    type: "category",
    category: "other",
    options: [
      { id: "oth_q15_opt1", text: "Extremely effectively", score: 5 },
      { id: "oth_q15_opt2", text: "Mostly effectively", score: 4 },
      { id: "oth_q15_opt3", text: "Sometimes effectively", score: 3 },
      { id: "oth_q15_opt4", text: "Rarely effectively", score: 2 },
      { id: "oth_q15_opt5", text: "Unable to cope at all", score: 1 },
    ],
  },
];
