import { AssessmentQuestion } from "../types";

export const parentQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "parental_burnout",
    text: "How often do you feel physically or emotionally exhausted from parenting responsibilities?",
    description: "Parenting is a 24/7 role that can lead to deep burnout without adequate rest.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q6_opt1", text: "Almost never", score: 5 },
      { id: "par_q6_opt2", text: "Occasionally", score: 4 },
      { id: "par_q6_opt3", text: "Sometimes", score: 3 },
      { id: "par_q6_opt4", text: "Frequently", score: 2 },
      { id: "par_q6_opt5", text: "Almost constantly", score: 1 },
    ],
  },
  {
    id: 7,
    key: "parental_self_care",
    text: "How much time are you able to carve out for yourself for hobbies, relaxation, or self-care?",
    description: "Personal time is essential to recharge your patience and resilience.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q7_opt1", text: "Adequate time daily", score: 5 },
      { id: "par_q7_opt2", text: "Some time most days", score: 4 },
      { id: "par_q7_opt3", text: "A little time occasionally", score: 3 },
      { id: "par_q7_opt4", text: "Rarely any time", score: 2 },
      { id: "par_q7_opt5", text: "No time for myself at all", score: 1 },
    ],
  },
  {
    id: 8,
    key: "mindful_patience",
    text: "How would you rate your level of patience and emotional calm when dealing with your kids?",
    description: "A parent's patience fluctuates with their own stress and fatigue levels.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q8_opt1", text: "Very patient & calm", score: 5 },
      { id: "par_q8_opt2", text: "Mostly patient", score: 4 },
      { id: "par_q8_opt3", text: "Sometimes irritable", score: 3 },
      { id: "par_q8_opt4", text: "Frequently lose patience", score: 2 },
      { id: "par_q8_opt5", text: "Extremely stressed / impatient", score: 1 },
    ],
  },
  {
    id: 9,
    key: "parenting_support",
    text: "How supported do you feel by your partner, family, or friends in sharing child care duties?",
    description: "Sharing the load is key to maintaining mental and physical health.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q9_opt1", text: "Extremely supported", score: 5 },
      { id: "par_q9_opt2", text: "Mostly supported", score: 4 },
      { id: "par_q9_opt3", text: "Sometimes supported", score: 3 },
      { id: "par_q9_opt4", text: "Rarely supported", score: 2 },
      { id: "par_q9_opt5", text: "Completely alone in parenting", score: 1 },
    ],
  },
  {
    id: 10,
    key: "child_worry",
    text: "How often do you feel anxious or overly worried about your children's development, grades, or health?",
    description: "Hyper-vigilance about children is a major source of parental anxiety.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q10_opt1", text: "Almost never", score: 5 },
      { id: "par_q10_opt2", text: "Rarely", score: 4 },
      { id: "par_q10_opt3", text: "Sometimes", score: 3 },
      { id: "par_q10_opt4", text: "Frequently", score: 2 },
      { id: "par_q10_opt5", text: "Constantly worrying", score: 1 },
    ],
  },
  {
    id: 11,
    key: "parental_alignment",
    text: "How aligned are you and your partner (or co-parent) on parenting decisions and rules?",
    description: "Co-parenting harmony reduces domestic stress levels significantly.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q11_opt1", text: "Perfectly aligned", score: 5 },
      { id: "par_q11_opt2", text: "Mostly aligned", score: 4 },
      { id: "par_q11_opt3", text: "Sometimes disagree", score: 3 },
      { id: "par_q11_opt4", text: "Frequent arguments", score: 2 },
      { id: "par_q11_opt5", text: "Completely misaligned", score: 1 },
    ],
  },
  {
    id: 12,
    key: "work_parenting_balance",
    text: "How effectively are you balancing your professional commitments with parenting?",
    description: "Balancing career and family causes constant role conflict for parents.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q12_opt1", text: "Very effectively", score: 5 },
      { id: "par_q12_opt2", text: "Mostly effectively", score: 4 },
      { id: "par_q12_opt3", text: "Sometimes challenging", score: 3 },
      { id: "par_q12_opt4", text: "Frequently difficult", score: 2 },
      { id: "par_q12_opt5", text: "Completely overwhelmed", score: 1 },
    ],
  },
  {
    id: 13,
    key: "emotional_bonding",
    text: "How satisfied are you with the depth of emotional connection you share with your kids?",
    description: "Quality bonding time reinforces positive parenting loops.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q13_opt1", text: "Extremely satisfied", score: 5 },
      { id: "par_q13_opt2", text: "Mostly satisfied", score: 4 },
      { id: "par_q13_opt3", text: "Sometimes distant", score: 3 },
      { id: "par_q13_opt4", text: "Rarely connect deeply", score: 2 },
      { id: "par_q13_opt5", text: "Highly disconnected", score: 1 },
    ],
  },
  {
    id: 14,
    key: "child_expenses",
    text: "How much financial stress does raising children (schooling, healthcare, clothes) cause you?",
    description: "Child-rearing expenses are a primary component of household budget pressure.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q14_opt1", text: "No stress at all", score: 5 },
      { id: "par_q14_opt2", text: "Minimal stress", score: 4 },
      { id: "par_q14_opt3", text: "Moderate stress", score: 3 },
      { id: "par_q14_opt4", text: "High stress", score: 2 },
      { id: "par_q14_opt5", text: "Severe financial crisis", score: 1 },
    ],
  },
  {
    id: 15,
    key: "parental_isolation",
    text: "How often do you feel lonely or isolated from your adult peers since becoming a parent?",
    description: "Parental isolation occurs when child-rearing displaces personal networks.",
    type: "category",
    category: "parent",
    options: [
      { id: "par_q15_opt1", text: "Never isolated", score: 5 },
      { id: "par_q15_opt2", text: "Rarely isolated", score: 4 },
      { id: "par_q15_opt3", text: "Sometimes lonely", score: 3 },
      { id: "par_q15_opt4", text: "Frequently isolated", score: 2 },
      { id: "par_q15_opt5", text: "Extremely isolated", score: 1 },
    ],
  },
];
