import { AssessmentQuestion } from "../types";

export const seniorCitizenQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "mobility_vitality",
    text: "How much do physical health limitations or mobility issues restrict your daily activities?",
    description: "Maintaining vitality despite physical limitations is key to emotional well-being.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q6_opt1", text: "Not at all / very vital", score: 5 },
      { id: "snr_q6_opt2", text: "Slight limitations", score: 4 },
      { id: "snr_q6_opt3", text: "Moderate impact", score: 3 },
      { id: "snr_q6_opt4", text: "Significant limitations", score: 2 },
      { id: "snr_q6_opt5", text: "Severe impact / homebound", score: 1 },
    ],
  },
  {
    id: 7,
    key: "social_connection",
    text: "How often do you feel lonely, isolated, or disconnected from friends and family?",
    description: "Social isolation in later life is a leading risk factor for depression.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q7_opt1", text: "Almost never", score: 5 },
      { id: "snr_q7_opt2", text: "Occasionally", score: 4 },
      { id: "snr_q7_opt3", text: "Sometimes", score: 3 },
      { id: "snr_q7_opt4", text: "Frequently", score: 2 },
      { id: "snr_q7_opt5", text: "Almost every day", score: 1 },
    ],
  },
  {
    id: 8,
    key: "daily_purpose",
    text: "How satisfied are you with your daily activities, hobbies, and sense of purpose?",
    description: "Finding new avenues of contribution and purpose supports cognitive longevity.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q8_opt1", text: "Very satisfied", score: 5 },
      { id: "snr_q8_opt2", text: "Mostly satisfied", score: 4 },
      { id: "snr_q8_opt3", text: "Somewhat neutral", score: 3 },
      { id: "snr_q8_opt4", text: "Slightly dissatisfied", score: 2 },
      { id: "snr_q8_opt5", text: "Extremely dissatisfied", score: 1 },
    ],
  },
  {
    id: 9,
    key: "cognitive_wellness",
    text: "How confident do you feel about your memory, mental clarity, and focus recently?",
    description: "Cognitive confidence promotes independent living and reduces aging anxiety.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q9_opt1", text: "Very confident", score: 5 },
      { id: "snr_q9_opt2", text: "Mostly confident", score: 4 },
      { id: "snr_q9_opt3", text: "Sometimes forgetful", score: 3 },
      { id: "snr_q9_opt4", text: "Very concerned", score: 2 },
      { id: "snr_q9_opt5", text: "Highly impaired", score: 1 },
    ],
  },
  {
    id: 10,
    key: "retirement_finances",
    text: "How comfortable or secure do you feel about your pension, savings, or retirement finances?",
    description: "Financial security in retirement provides fundamental peace of mind.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q10_opt1", text: "Very secure", score: 5 },
      { id: "snr_q10_opt2", text: "Mostly secure", score: 4 },
      { id: "snr_q10_opt3", text: "Neutral / ok", score: 3 },
      { id: "snr_q10_opt4", text: "Slightly insecure", score: 2 },
      { id: "snr_q10_opt5", text: "Highly stressed / insecure", score: 1 },
    ],
  },
  {
    id: 11,
    key: "independent_living",
    text: "How satisfied are you with your current living arrangements and degree of independence?",
    description: "Maintaining autonomy and comfort in your home supports emotional health.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q11_opt1", text: "Very satisfied", score: 5 },
      { id: "snr_q11_opt2", text: "Mostly satisfied", score: 4 },
      { id: "snr_q11_opt3", text: "Somewhat neutral", score: 3 },
      { id: "snr_q11_opt4", text: "Dissatisfied", score: 2 },
      { id: "snr_q11_opt5", text: "Extremely unhappy / dependent", score: 1 },
    ],
  },
  {
    id: 12,
    key: "care_access",
    text: "How confident are you that you can access quality medical or helper care when needed?",
    description: "Knowing care is within reach reduces subconscious health anxiety.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q12_opt1", text: "Extremely confident", score: 5 },
      { id: "snr_q12_opt2", text: "Mostly confident", score: 4 },
      { id: "snr_q12_opt3", text: "Sometimes worried", score: 3 },
      { id: "snr_q12_opt4", text: "Frequently worried", score: 2 },
      { id: "snr_q12_opt5", text: "No access to care at all", score: 1 },
    ],
  },
  {
    id: 13,
    key: "life_reflection",
    text: "How much peace and acceptance do you feel when reflecting on your life achievements?",
    description: "Integrity vs. despair is the key psychological stage of older age.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q13_opt1", text: "Deep peace & acceptance", score: 5 },
      { id: "snr_q13_opt2", text: "Mostly positive", score: 4 },
      { id: "snr_q13_opt3", text: "Neutral / mixed thoughts", score: 3 },
      { id: "snr_q13_opt4", text: "Frequently regretful", score: 2 },
      { id: "snr_q13_opt5", text: "Severe despair / sadness", score: 1 },
    ],
  },
  {
    id: 14,
    key: "sleep_restiveness",
    text: "How rested do you feel after sleep, taking into account any disruptions or early waking?",
    description: "Sleep quality often shifts with age, affecting emotional balance.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q14_opt1", text: "Extremely rested", score: 5 },
      { id: "snr_q14_opt2", text: "Mostly rested", score: 4 },
      { id: "snr_q14_opt3", text: "Sometimes restless", score: 3 },
      { id: "snr_q14_opt4", text: "Poor sleep on many nights", score: 2 },
      { id: "snr_q14_opt5", text: "Very poor / insomniac", score: 1 },
    ],
  },
  {
    id: 15,
    key: "grief_coping",
    text: "How effectively are you coping with the loss or absence of friends, peers, or loved ones?",
    description: "Coping with grief is a major recurring stressor in later adulthood.",
    type: "category",
    category: "senior_citizen",
    options: [
      { id: "snr_q15_opt1", text: "Extremely effectively / at peace", score: 5 },
      { id: "snr_q15_opt2", text: "Mostly manageable", score: 4 },
      { id: "snr_q15_opt3", text: "Sometimes painful", score: 3 },
      { id: "snr_q15_opt4", text: "Frequently sad / grieving", score: 2 },
      { id: "snr_q15_opt5", text: "Severely overwhelmed by grief", score: 1 },
    ],
  },
];
