import { AssessmentQuestion } from "../types";

export const studentQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "academic_pressure",
    text: "How often have you felt overwhelmed by academic deadlines or exam preparation recently?",
    description: "Tracking study stress helps identify when workloads become difficult to handle.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q6_opt1", text: "Almost never", score: 5 },
      { id: "stud_q6_opt2", text: "Occasionally", score: 4 },
      { id: "stud_q6_opt3", text: "Sometimes", score: 3 },
      { id: "stud_q6_opt4", text: "Frequently", score: 2 },
      { id: "stud_q6_opt5", text: "Almost constantly", score: 1 },
    ],
  },
  {
    id: 7,
    key: "peer_support",
    text: "How connected and supported do you feel by your friends or study groups?",
    description: "Peer connection provides critical emotional support during academic challenges.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q7_opt1", text: "Extremely supported", score: 5 },
      { id: "stud_q7_opt2", text: "Mostly supported", score: 4 },
      { id: "stud_q7_opt3", text: "Sometimes supported", score: 3 },
      { id: "stud_q7_opt4", text: "Rarely supported", score: 2 },
      { id: "stud_q7_opt5", text: "Not supported at all", score: 1 },
    ],
  },
  {
    id: 8,
    key: "academic_focus",
    text: "How easy has it been for you to focus during class or study hours?",
    description: "Cognitive focus can fluctuate significantly with high stress or lack of rest.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q8_opt1", text: "Very easy to focus", score: 5 },
      { id: "stud_q8_opt2", text: "Mostly focused", score: 4 },
      { id: "stud_q8_opt3", text: "Sometimes distracted", score: 3 },
      { id: "stud_q8_opt4", text: "Highly distracted", score: 2 },
      { id: "stud_q8_opt5", text: "Unable to focus at all", score: 1 },
    ],
  },
  {
    id: 9,
    key: "future_clarity",
    text: "How optimistic and clear do you feel about your future career or academic path?",
    description: "Uncertainty about the future is a major driver of student anxiety.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q9_opt1", text: "Very optimistic & clear", score: 5 },
      { id: "stud_q9_opt2", text: "Mostly positive", score: 4 },
      { id: "stud_q9_opt3", text: "Somewhat neutral", score: 3 },
      { id: "stud_q9_opt4", text: "Anxious & uncertain", score: 2 },
      { id: "stud_q9_opt5", text: "Completely lost", score: 1 },
    ],
  },
  {
    id: 10,
    key: "extracurricular_balance",
    text: "How well are you balancing schoolwork with self-care, hobbies, and social life?",
    description: "Maintaining a balanced routine is essential to prevent academic burnout.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q10_opt1", text: "Excellently balanced", score: 5 },
      { id: "stud_q10_opt2", text: "Mostly balanced", score: 4 },
      { id: "stud_q10_opt3", text: "Sometimes balanced", score: 3 },
      { id: "stud_q10_opt4", text: "Rarely balanced", score: 2 },
      { id: "stud_q10_opt5", text: "Completely out of balance", score: 1 },
    ],
  },
  {
    id: 11,
    key: "school_belonging",
    text: "How much do you feel you belong and are accepted in your current educational institution?",
    description: "A sense of belonging supports confidence and social wellness.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q11_opt1", text: "Completely at home", score: 5 },
      { id: "stud_q11_opt2", text: "Mostly belong", score: 4 },
      { id: "stud_q11_opt3", text: "Neutral / ok", score: 3 },
      { id: "stud_q11_opt4", text: "Feel somewhat isolated", score: 2 },
      { id: "stud_q11_opt5", text: "Like an complete outsider", score: 1 },
    ],
  },
  {
    id: 12,
    key: "student_finances",
    text: "How often do concerns about tuition, living costs, or student debt cause you worry?",
    description: "Financial strain is a major secondary stressor for students.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q12_opt1", text: "Never worry", score: 5 },
      { id: "stud_q12_opt2", text: "Rarely worry", score: 4 },
      { id: "stud_q12_opt3", text: "Sometimes worry", score: 3 },
      { id: "stud_q12_opt4", text: "Frequently worry", score: 2 },
      { id: "stud_q12_opt5", text: "Constantly stressed by money", score: 1 },
    ],
  },
  {
    id: 13,
    key: "academic_confidence",
    text: "How confident do you feel in your ability to master your coursework and pass exams?",
    description: "Self-efficacy plays a major role in academic stress management.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q13_opt1", text: "Highly confident", score: 5 },
      { id: "stud_q13_opt2", text: "Mostly confident", score: 4 },
      { id: "stud_q13_opt3", text: "Sometimes confident", score: 3 },
      { id: "stud_q13_opt4", text: "Rarely confident", score: 2 },
      { id: "stud_q13_opt5", text: "Not confident at all", score: 1 },
    ],
  },
  {
    id: 14,
    key: "family_academic_expectations",
    text: "How comfortable are you handling family expectations or pressure regarding your grades?",
    description: "Managing parental expectations is a common source of interpersonal stress.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q14_opt1", text: "Very comfortable / supported", score: 5 },
      { id: "stud_q14_opt2", text: "Mostly manageable", score: 4 },
      { id: "stud_q14_opt3", text: "Sometimes pressured", score: 3 },
      { id: "stud_q14_opt4", text: "Frequently stressed by expectations", score: 2 },
      { id: "stud_q14_opt5", text: "Severely overwhelmed by pressure", score: 1 },
    ],
  },
  {
    id: 15,
    key: "exam_anxiety",
    text: "How effectively do you manage feelings of anxiety or panic during tests or assessments?",
    description: "Developing exam coping skills prevents acute stress blocks.",
    type: "category",
    category: "student",
    options: [
      { id: "stud_q15_opt1", text: "Extremely effectively", score: 5 },
      { id: "stud_q15_opt2", text: "Mostly effectively", score: 4 },
      { id: "stud_q15_opt3", text: "Sometimes effectively", score: 3 },
      { id: "stud_q15_opt4", text: "Rarely effectively", score: 2 },
      { id: "stud_q15_opt5", text: "Not able to manage it at all", score: 1 },
    ],
  },
];
