import { AssessmentQuestion } from "../types";

export const womenQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "role_overload",
    text: "How often do you feel pressured by balancing multiple roles (career, domestic duties, caretaking)?",
    description: "Societal and personal expectations on women often lead to chronic role overload.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q6_opt1", text: "Almost never", score: 5 },
      { id: "wmn_q6_opt2", text: "Occasionally", score: 4 },
      { id: "wmn_q6_opt3", text: "Sometimes", score: 3 },
      { id: "wmn_q6_opt4", text: "Frequently", score: 2 },
      { id: "wmn_q6_opt5", text: "Almost constantly overwhelmed", score: 1 },
    ],
  },
  {
    id: 7,
    key: "physical_health_mood",
    text: "How much do hormonal cycles, physical health changes, or sleep disruptions affect your mood?",
    description: "Recognizing biology's impact on mood is vital for self-compassion and care.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q7_opt1", text: "Minimal impact / very stable", score: 5 },
      { id: "wmn_q7_opt2", text: "Slight manageable impact", score: 4 },
      { id: "wmn_q7_opt3", text: "Moderate monthly impact", score: 3 },
      { id: "wmn_q7_opt4", text: "Significant impact on daily life", score: 2 },
      { id: "wmn_q7_opt5", text: "Severe debilitating impact", score: 1 },
    ],
  },
  {
    id: 8,
    key: "women_sisterhood",
    text: "How satisfied are you with the support, trust, and depth of your friendships with other women?",
    description: "Peer connection provides a vital psychological shield against depression and stress.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q8_opt1", text: "Very satisfied / highly supported", score: 5 },
      { id: "wmn_q8_opt2", text: "Mostly satisfied", score: 4 },
      { id: "wmn_q8_opt3", text: "Somewhat satisfied", score: 3 },
      { id: "wmn_q8_opt4", text: "Dissatisfied / lonely", score: 2 },
      { id: "wmn_q8_opt5", text: "Completely isolated", score: 1 },
    ],
  },
  {
    id: 9,
    key: "boundary_setting",
    text: "How comfortably can you say 'no' to others' requests without feeling guilt or anxiety?",
    description: "Setting boundaries is essential for emotional health and preventing energy depletion.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q9_opt1", text: "Extremely comfortably", score: 5 },
      { id: "wmn_q9_opt2", text: "Mostly comfortably", score: 4 },
      { id: "wmn_q9_opt3", text: "Sometimes struggle / feel guilty", score: 3 },
      { id: "wmn_q9_opt4", text: "Rarely set boundaries", score: 2 },
      { id: "wmn_q9_opt5", text: "Unable to say 'no' ever", score: 1 },
    ],
  },
  {
    id: 10,
    key: "self_image",
    text: "How satisfied and compassionate do you feel towards your body and self-image?",
    description: "Self-acceptance buffers against negative societal messages and low self-esteem.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q10_opt1", text: "Extremely satisfied & accepting", score: 5 },
      { id: "wmn_q10_opt2", text: "Mostly positive", score: 4 },
      { id: "wmn_q10_opt3", text: "Neutral / ok", score: 3 },
      { id: "wmn_q10_opt4", text: "Frequently critical of myself", score: 2 },
      { id: "wmn_q10_opt5", text: "Severe self-dislike / distress", score: 1 },
    ],
  },
  {
    id: 11,
    key: "personal_safety",
    text: "How safe and secure do you feel in your daily work, transit, or neighborhood environments?",
    description: "Safety worries can create chronic hyper-vigilance and subconscious anxiety.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q11_opt1", text: "Completely safe & secure", score: 5 },
      { id: "wmn_q11_opt2", text: "Mostly safe", score: 4 },
      { id: "wmn_q11_opt3", text: "Sometimes anxious in public", score: 3 },
      { id: "wmn_q11_opt4", text: "Frequently feel unsafe", score: 2 },
      { id: "wmn_q11_opt5", text: "Constantly fear for my safety", score: 1 },
    ],
  },
  {
    id: 12,
    key: "gender_equality_work",
    text: "How respected and equally valued do you feel in your workplace or academic environment?",
    description: "Systemic bias or underappreciation affects long-term mental stamina.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q12_opt1", text: "Fully respected & equal", score: 5 },
      { id: "wmn_q12_opt2", text: "Mostly respected", score: 4 },
      { id: "wmn_q12_opt3", text: "Neutral / average respect", score: 3 },
      { id: "wmn_q12_opt4", text: "Felt somewhat sidelined", score: 2 },
      { id: "wmn_q12_opt5", text: "Severely marginalized / disrespected", score: 1 },
    ],
  },
  {
    id: 13,
    key: "wellness_time",
    text: "How effectively do you protect daily time dedicated strictly to your personal mental health?",
    description: "Prioritizing your own wellness is key to sustaining support for others.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q13_opt1", text: "Very effectively", score: 5 },
      { id: "wmn_q13_opt2", text: "Mostly effectively", score: 4 },
      { id: "wmn_q13_opt3", text: "Sometimes effectively", score: 3 },
      { id: "wmn_q13_opt4", text: "Rarely prioritize myself", score: 2 },
      { id: "wmn_q13_opt5", text: "Never get wellness time", score: 1 },
    ],
  },
  {
    id: 14,
    key: "life_transitions",
    text: "How effectively are you coping with recent major life transitions (family, motherhood, aging)?",
    description: "Transitions create emotional stress cycles that require careful adaptation.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q14_opt1", text: "Coping extremely well", score: 5 },
      { id: "wmn_q14_opt2", text: "Mostly manageable", score: 4 },
      { id: "wmn_q14_opt3", text: "Sometimes stressful", score: 3 },
      { id: "wmn_q14_opt4", text: "Highly difficult to cope", score: 2 },
      { id: "wmn_q14_opt5", text: "Completely overwhelmed / crisis", score: 1 },
    ],
  },
  {
    id: 15,
    key: "authentic_expression",
    text: "How safe do you feel expressing your authentic feelings, needs, or opinions at home?",
    description: "Suppression of needs is strongly correlated with emotional fatigue.",
    type: "category",
    category: "women",
    options: [
      { id: "wmn_q15_opt1", text: "Completely safe", score: 5 },
      { id: "wmn_q15_opt2", text: "Mostly safe", score: 4 },
      { id: "wmn_q15_opt3", text: "Sometimes hesitant", score: 3 },
      { id: "wmn_q15_opt4", text: "Rarely express myself", score: 2 },
      { id: "wmn_q15_opt5", text: "Silenced / unsafe to share", score: 1 },
    ],
  },
];
