import { AssessmentQuestion } from "../types";

export const workingProfessionalQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "workload_burnout",
    text: "How often have you felt physically or emotionally exhausted due to your workload?",
    description: "Chronic stress at work is a leading cause of burnout and fatigue.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q6_opt1", text: "Almost never", score: 5 },
      { id: "wp_q6_opt2", text: "Occasionally", score: 4 },
      { id: "wp_q6_opt3", text: "Sometimes", score: 3 },
      { id: "wp_q6_opt4", text: "Frequently", score: 2 },
      { id: "wp_q6_opt5", text: "Almost constantly", score: 1 },
    ],
  },
  {
    id: 7,
    key: "work_life_harmony",
    text: "How satisfied are you with the boundary between your work commitments and personal life?",
    description: "Maintaining clear boundaries ensures time for rest, connection, and hobbies.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q7_opt1", text: "Very satisfied", score: 5 },
      { id: "wp_q7_opt2", text: "Mostly satisfied", score: 4 },
      { id: "wp_q7_opt3", text: "Somewhat neutral", score: 3 },
      { id: "wp_q7_opt4", text: "Slightly dissatisfied", score: 2 },
      { id: "wp_q7_opt5", text: "Extremely dissatisfied", score: 1 },
    ],
  },
  {
    id: 8,
    key: "workplace_conflict",
    text: "How often do team friction or difficult workplace communications impact your peace of mind?",
    description: "Interpersonal issues at work can be mentally taxing to process.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q8_opt1", text: "Almost never", score: 5 },
      { id: "wp_q8_opt2", text: "Rarely", score: 4 },
      { id: "wp_q8_opt3", text: "Sometimes", score: 3 },
      { id: "wp_q8_opt4", text: "Frequently", score: 2 },
      { id: "wp_q8_opt5", text: "Almost every day", score: 1 },
    ],
  },
  {
    id: 9,
    key: "professional_recognition",
    text: "How valued and appreciated do you feel for your work contributions?",
    description: "Feeling recognized boosts morale and provides intrinsic motivation.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q9_opt1", text: "Highly valued", score: 5 },
      { id: "wp_q9_opt2", text: "Mostly valued", score: 4 },
      { id: "wp_q9_opt3", text: "Somewhat neutral", score: 3 },
      { id: "wp_q9_opt4", text: "Underappreciated", score: 2 },
      { id: "wp_q9_opt5", text: "Not valued at all", score: 1 },
    ],
  },
  {
    id: 10,
    key: "stress_recovery",
    text: "How effectively are you practicing daily self-care habits or stress relief methods?",
    description: "Dedicated daily habits help reset your stress response cycle.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q10_opt1", text: "Extremely effectively", score: 5 },
      { id: "wp_q10_opt2", text: "Mostly effectively", score: 4 },
      { id: "wp_q10_opt3", text: "Sometimes effectively", score: 3 },
      { id: "wp_q10_opt4", text: "Rarely effectively", score: 2 },
      { id: "wp_q10_opt5", text: "Not practicing at all", score: 1 },
    ],
  },
  {
    id: 11,
    key: "commute_fatigue",
    text: "How much stress or physical fatigue does your daily travel or remote-work setup cause?",
    description: "Commuting hours or isolation in remote work affects daily energy baselines.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q11_opt1", text: "No stress / very smooth", score: 5 },
      { id: "wp_q11_opt2", text: "Minimal fatigue", score: 4 },
      { id: "wp_q11_opt3", text: "Moderate fatigue", score: 3 },
      { id: "wp_q11_opt4", text: "Highly stressful", score: 2 },
      { id: "wp_q11_opt5", text: "Extremely exhausting", score: 1 },
    ],
  },
  {
    id: 12,
    key: "career_growth",
    text: "How satisfied are you with your long-term career growth and progression opportunities?",
    description: "Stagnation or pressure to perform affects workplace mental health.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q12_opt1", text: "Very satisfied", score: 5 },
      { id: "wp_q12_opt2", text: "Mostly satisfied", score: 4 },
      { id: "wp_q12_opt3", text: "Neutral / ok", score: 3 },
      { id: "wp_q12_opt4", text: "Dissatisfied", score: 2 },
      { id: "wp_q12_opt5", text: "Extremely frustrated / stuck", score: 1 },
    ],
  },
  {
    id: 13,
    key: "job_autonomy",
    text: "How much control and decision-making power do you have over your daily work tasks?",
    description: "A sense of control (autonomy) is a key psychological need at work.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q13_opt1", text: "Complete autonomy", score: 5 },
      { id: "wp_q13_opt2", text: "High autonomy", score: 4 },
      { id: "wp_q13_opt3", text: "Moderate autonomy", score: 3 },
      { id: "wp_q13_opt4", text: "Low autonomy", score: 2 },
      { id: "wp_q13_opt5", text: "No control / micromanaged", score: 1 },
    ],
  },
  {
    id: 14,
    key: "financial_planning",
    text: "How often do you worry about long-term financial security, investments, or household savings?",
    description: "Financial anxiety in working adults affects general emotional stability.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q14_opt1", text: "Almost never", score: 5 },
      { id: "wp_q14_opt2", text: "Rarely", score: 4 },
      { id: "wp_q14_opt3", text: "Sometimes", score: 3 },
      { id: "wp_q14_opt4", text: "Frequently", score: 2 },
      { id: "wp_q14_opt5", text: "Almost constantly", score: 1 },
    ],
  },
  {
    id: 15,
    key: "post_work_energy",
    text: "How much physical or mental energy do you have left at the end of the workday for hobbies or family?",
    description: "Residual energy after work is a major indicator of overall wellness.",
    type: "category",
    category: "working_professional",
    options: [
      { id: "wp_q15_opt1", text: "Plenty of energy", score: 5 },
      { id: "wp_q15_opt2", text: "Mostly energetic", score: 4 },
      { id: "wp_q15_opt3", text: "Somewhat tired", score: 3 },
      { id: "wp_q15_opt4", text: "Very depleted", score: 2 },
      { id: "wp_q15_opt5", text: "Completely exhausted / empty", score: 1 },
    ],
  },
];
