import { AssessmentQuestion } from "../types";

export const youngProfessionalQuestions: AssessmentQuestion[] = [
  {
    id: 6,
    key: "career_direction",
    text: "How optimistic and clear do you feel about your early career path and future growth?",
    description: "Finding professional direction is a key developmental stressor in early careers.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q6_opt1", text: "Very optimistic & clear", score: 5 },
      { id: "yp_q6_opt2", text: "Mostly positive", score: 4 },
      { id: "yp_q6_opt3", text: "Somewhat neutral", score: 3 },
      { id: "yp_q6_opt4", text: "Anxious & uncertain", score: 2 },
      { id: "yp_q6_opt5", text: "Completely lost", score: 1 },
    ],
  },
  {
    id: 7,
    key: "office_adjustment",
    text: "How easily have you adjusted to the routines, culture, and expectations of professional work life?",
    description: "Transitioning from college or casual work to corporate routines can be taxing.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q7_opt1", text: "Very easily", score: 5 },
      { id: "yp_q7_opt2", text: "Mostly adjusted", score: 4 },
      { id: "yp_q7_opt3", text: "Sometimes challenging", score: 3 },
      { id: "yp_q7_opt4", text: "Difficult to cope with", score: 2 },
      { id: "yp_q7_opt5", text: "Completely overwhelming", score: 1 },
    ],
  },
  {
    id: 8,
    key: "financial_independence",
    text: "How confident are you in managing your bills, rent, and early financial independence?",
    description: "Managing primary personal finances is a foundational life stressor.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q8_opt1", text: "Highly confident", score: 5 },
      { id: "yp_q8_opt2", text: "Mostly confident", score: 4 },
      { id: "yp_q8_opt3", text: "Sometimes anxious", score: 3 },
      { id: "yp_q8_opt4", text: "Very stressed about finances", score: 2 },
      { id: "yp_q8_opt5", text: "Unable to manage / broke", score: 1 },
    ],
  },
  {
    id: 9,
    key: "adult_friendships",
    text: "How satisfied are you with your social life and ability to build adult friendships post-graduation?",
    description: "Building new support networks in adulthood prevents feelings of isolation.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q9_opt1", text: "Very satisfied", score: 5 },
      { id: "yp_q9_opt2", text: "Mostly satisfied", score: 4 },
      { id: "yp_q9_opt3", text: "Somewhat lonely", score: 3 },
      { id: "yp_q9_opt4", text: "Mainly isolated", score: 2 },
      { id: "yp_q9_opt5", text: "Extremely lonely", score: 1 },
    ],
  },
  {
    id: 10,
    key: "job_stability",
    text: "How secure or stable do you feel in your current job or internship role?",
    description: "Job market volatility is a primary driver of young professional anxiety.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q10_opt1", text: "Completely secure", score: 5 },
      { id: "yp_q10_opt2", text: "Mostly secure", score: 4 },
      { id: "yp_q10_opt3", text: "Neutral / unsure", score: 3 },
      { id: "yp_q10_opt4", text: "Slightly insecure", score: 2 },
      { id: "yp_q10_opt5", text: "Extremely insecure / temporary", score: 1 },
    ],
  },
  {
    id: 11,
    key: "assertiveness",
    text: "How comfortable do you feel voicing your opinions or setting boundaries with senior team members?",
    description: "Confidence in communication is key to preventing workplace exploitation.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q11_opt1", text: "Very comfortable", score: 5 },
      { id: "yp_q11_opt2", text: "Mostly comfortable", score: 4 },
      { id: "yp_q11_opt3", text: "Sometimes hesitant", score: 3 },
      { id: "yp_q11_opt4", text: "Rarely speak up", score: 2 },
      { id: "yp_q11_opt5", text: "Too intimidated to speak up", score: 1 },
    ],
  },
  {
    id: 12,
    key: "learning_burnout",
    text: "How often do you feel exhausted by the rapid learning curves and training demands of your job?",
    description: "High cognitive loads from new skill acquisition can lead to early burnout.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q12_opt1", text: "Never exhausted", score: 5 },
      { id: "yp_q12_opt2", text: "Rarely exhausted", score: 4 },
      { id: "yp_q12_opt3", text: "Sometimes exhausted", score: 3 },
      { id: "yp_q12_opt4", text: "Frequently exhausted", score: 2 },
      { id: "yp_q12_opt5", text: "Constantly drained", score: 1 },
    ],
  },
  {
    id: 13,
    key: "work_life_integration",
    text: "How well do you balance working hours with your personal interests, hobbies, or relationships?",
    description: "Finding a functional work-life rhythm is critical in early adulthood.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q13_opt1", text: "Excellently integrated", score: 5 },
      { id: "yp_q13_opt2", text: "Mostly balanced", score: 4 },
      { id: "yp_q13_opt3", text: "Sometimes off-balance", score: 3 },
      { id: "yp_q13_opt4", text: "Rarely have personal time", score: 2 },
      { id: "yp_q13_opt5", text: "No life outside work", score: 1 },
    ],
  },
  {
    id: 14,
    key: "mentorship_support",
    text: "How supported do you feel by direct managers, mentors, or HR in your workplace?",
    description: "Workplace mentorship acts as a major protective factor against stress.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q14_opt1", text: "Extremely supported", score: 5 },
      { id: "yp_q14_opt2", text: "Mostly supported", score: 4 },
      { id: "yp_q14_opt3", text: "Neutral / average support", score: 3 },
      { id: "yp_q14_opt4", text: "Rarely supported", score: 2 },
      { id: "yp_q14_opt5", text: "Not supported at all", score: 1 },
    ],
  },
  {
    id: 15,
    key: "imposter_syndrome",
    text: "How often do you worry that you aren't actually qualified for your role (imposter feelings)?",
    description: "Imposter feelings are highly prevalent in early professional transitions.",
    type: "category",
    category: "young_pro",
    options: [
      { id: "yp_q15_opt1", text: "Never feel this way", score: 5 },
      { id: "yp_q15_opt2", text: "Rarely feel this way", score: 4 },
      { id: "yp_q15_opt3", text: "Sometimes feel this way", score: 3 },
      { id: "yp_q15_opt4", text: "Frequently feel this way", score: 2 },
      { id: "yp_q15_opt5", text: "Constantly feel unqualified", score: 1 },
    ],
  },
];
